"""Initial Migration

Revision ID: 82a2bb165977
Revises: 
Create Date: 2022-05-18 15:01:45.454902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a2bb165977'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('location', sa.String(length=255), nullable=True))
    op.alter_column('assets', 'worth',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    op.alter_column('assets', 'worth',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('assets', 'location')
    # ### end Alembic commands ###
